development:
  adapter: mysql
  database: ts_demo_dev
  username: root
  password:

test:
  adapter: mysql
  database: ts_demo_test
  username: root
  password:

production:
  adapter: mysql
  database: ts_demo_prod
  username: root
  password:
